# push to github, test code and push badge to repo front page
name: Running tests...

on:
  push:
    branches: [ master ]

jobs: 
  step1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3

    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: '3.8.4'

    - name: Run test
      env:
        S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
        S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
        SPRING_DATASOURCE_URL: ${{secrets.SPRING_DATASOURCE_URL}}
        SPRING_DATASOURCE_USERNAME: ${{secrets.SPRING_DATASOURCE_USERNAME}}
        SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
        SPRING_MAIL_USERNAME: ${{secrets.SPRING_MAIL_USERNAME}}
        SPRING_MAIL_PASSWORD: ${{secrets.SPRING_MAIL_PASSWORD}}
      run: mvn clean verify

    - name: Generate Jacoco badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true

    - name: Upload coverage badge to DO spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
          access_key: ${{secrets.DO_ACCESS_KEY}}
          secret_key: ${{secrets.DO_SECRET_KEY}}
          space_name: bigcontainer
          space_region: sgp1
          # source is the file that you wanna upload to DO
          source: .github/badges/jacoco.svg
          # out_dir is the output directory in DO 
          out_dir: coverage/${{github.event.repository.name}}
          # by default permission is already public-read
          permission: public-read
      
    - name: Upload whole jacoco coverage report
      uses: BetaHuhn/do-spaces-action@v2
      with:
          access_key: ${{secrets.DO_ACCESS_KEY}}
          secret_key: ${{secrets.DO_SECRET_KEY}}
          space_name: bigcontainer
          space_region: sgp1
          source: target/site/jacoco
          out_dir: coverage/${{github.event.repository.name}}